### ISSUE TITLE
Keeps saying cannot find module websocket

### ISSUE THREAD

**Issue by AlphaT3ch** [lrstanley/irccloud-uptime#4]
Yes, I have installed it with pip

**Comment by Liamraystanley** [comment]
I would confirm and see if it's **websocket** or **websocket-client**, as _they are not the same_.

Furthermore, confirm for me what version of **pip** you are using, as well as what your default Python version is (with `python -V`).

**Comment by AlphaT3ch** [comment]
Okay, I now have the modules working (out of date version) but it just keeps saying "Disconnected." I'm 100% sure the email/password combination is correct
